### ISSUE TITLE
Auto Correction of Hot Pixels

### ISSUE THREAD

**Issue by agentirons** [ampas/rawtoaces#103]
I can't seem to find any info on whether dcraw has already implemented this, but it would be great to have an option for interpolating around hot pixels in the raw image data automatically, rather than manually using a dark frame for each camera.

[Ufraw](http://ufraw.sourceforge.net/) seems to have added this as a feature, so that may be a good starting point.

**Comment by miaoqi** [comment]
I think "libraw" will fix the hot spots before demonsaicing . You can also post a question on libra's forum.

**Comment by miaoqi** [comment]
Hi, have you posted a question on "libraw" forum?

**Comment by agentirons** [comment]
Closing my issue as I don't have the time to implement the feature, maybe someone can take it up in the future.
