### ISSUE TITLE
use JSON file for data

### ISSUE THREAD

**Issue by miaoqi** [ampas/rawtoaces#26]
As @lchen198 suggest, there should be a common and standard format to host the data such as camera spectral sensitivity data.  "JSON" is one choice.

**Comment by KelSolaar** [comment]
Just pushing that from Slack for further discussion regarding #31:

Almost complete for me so in the light of doing that there might be some small changes to do, essentially attribute names, taking the stuff I was saying before:

- Both `model` and `catalog_number` are in use, any reasons for using both?
- Would like to rename `api_version` to `schema_version`.
- Tempted to rename `spectral_data` to `body`.
- Would like to rename `data` to `dataset` as we are dealing with multiple data set.
- `document_creation_date` should respect RFC 3339.
