### ISSUE TITLE
Change "Illuminate" to "Illuminant"

### ISSUE THREAD

**Issue by scottdyer** [ampas/rawtoaces#30]
I recognize this is a really stupid issue and _extremely_ minor in the grand scheme of things, but it's driving me crazy as I read the code.

At some point can we please do a find and replace across all files to change "**Illuminate**" (a verb) to "**Illuminant**" (a noun)?

**Comment by miaoqi** [comment]
Closes issue#30

**Comment by miaoqi** [comment]
This has been fixed. Please close #30
