### ISSUE TITLE
Neutral clipping issue for some cameras

### ISSUE THREAD

**Issue by miaoqi** [ampas/rawtoaces#41]
The Canon 1D MkIV, Fujifilm S5, Nikon D700 and Nikon D7000 did not have neutral clipping, due to the saturation point in the raw files being lower than the encoding maximum in some channels. Some information should be provided in the "README" about using the –S parameter to address this.

**Comment by aforsythe** [comment]
This issue was moved to http://www.acescentral.com/t/neutral-clipping-issue-for-some-cameras/1148
