### ISSUE TITLE
Unresolved symbols while building

### ISSUE THREAD

**Issue by aforsythe** [ampas/rawtoaces#49]
downloaded "github.com/ampas/rawtoaces" and tried to compile, but it looks like I have some unresolved symbols?

I did the mandatory..

    $ mkdir build && cd build
    $ cmake ..
    $ make
    $ sudo make install

cmake said this:

	-- The C compiler identification is unknown
	-- The CXX compiler identification is unknown
	-- Check for working C compiler: /usr/bin/cc
	-- Check for working C compiler: /usr/bin/cc -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Check for working CXX compiler: /usr/bin/c++
	-- Check for working CXX compiler: /usr/bin/c++ -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Found IlmBase, version 1.0.1
	-- Found AcesContainer, version 1.0.1
	-- Found LibRaw, version 0.15.4
	-- Found installed version of Eigen:
	-- Found required Ceres dependency: Eigen version 3.2.0 in /usr/include/eigen3
	-- Found required Ceres dependency: glog
	-- Looking for include file pthread.h
	-- Looking for include file pthread.h - found
	-- Looking for pthread_create
	-- Looking for pthread_create - not found
	-- Looking for pthread_create in pthreads
	-- Looking for pthread_create in pthreads - not found
	-- Looking for pthread_create in pthread
	-- Looking for pthread_create in pthread - found
	-- Performing Test GFLAGS_IN_GOOGLE_NAMESPACE
	-- Performing Test GFLAGS_IN_GOOGLE_NAMESPACE - Success
	-- Found required Ceres dependency: gflags
	-- Found Ceres version: 1.13.0 installed in: /usr/local with components: [LAPACK, SuiteSparse, SparseLinearAlgebraLibrary, CXSparse, SchurSpecializations, OpenMP]
	-- Found Boost_FOUND, version 105400
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /mnt/c/dev/rawtoaces-master [Downloaded]/build

	Compiling under Ubuntu (inside a Win10 installation). The exact output from "make" is:

	Scanning dependencies of target rawtoacesIDT
	[ 33%] Building CXX object lib/CMakeFiles/rawtoacesIDT.dir/rta.cpp.o
	Linking CXX shared library librawtoacesIDT.so
	/usr/bin/ld: CMakeFiles/rawtoacesIDT.dir/rta.cpp.o: Die Umlagerung von
	CMakeFiles/rawtoacesIDT.dir/rta.cpp.o: error adding symbols: Ung��ltiger Wert
	collect2: error: ld returned 1 exit status
	make[2]: *** [lib/librawtoacesIDT.so] Fehler 1
	make[1]: *** [lib/CMakeFiles/rawtoacesIDT.dir/all] Fehler 2
	make: *** [all] Fehler 2

(yes: the "��" are coming from my console)

What am I doing wrong?

**Comment by miaoqi** [comment]
What OS were you using? Ubuntu under WIN10?  I have installed it in Ubuntu many times and there are no issues. 

This is probably the cause:

"
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
"
I need to use the setting on that specific machine to debug. 

Meanwhile, please see this relevant post:

[https://stackoverflow.com/questions/24813827/cmake-failing-to-detect-pthreads-due-to-warnings/25130590#25130590](url)
