### ISSUE TITLE
Abort trap: 6

### ISSUE THREAD

**Issue by giardiello** [ampas/rawtoaces#52]
Hi!
Trying to use the tool to debayer a Sony Alfa 7 s II .ARW file.
Every time get into the same issue:

 Assertion failed: (outputBufferSize < 150e6), function configure, file /Users/giardiello/aces_container/aces_Writer.cpp, line 212.
Abort trap: 6

Any suggestion?

**Comment by miaoqi** [comment]
Hi @giardiello, thanks for pointing it out! Since one of the dependencies - "aces_container" currently has the size restraint for the output, please use the following flag (-h: half size) for "rawtoaces" if you can:

rawtoaces -h input.raw

**Comment by giardiello** [comment]
Thanks. Figured it and done it, it works. I will run more tests now.

Thanks,

Il giorno 30/mag/2017, alle ore 07:10, Miaoqi Zhu <notifications@github.com> ha scritto:
