### ISSUE TITLE
.DS_store files

### ISSUE THREAD

**Issue by scottdyer** [ampas/rawtoaces#58]
It appears that every time I reinstall to test updates, cmake is moving .DS_store files from `../rawtoaces/data/camera` into `/usr/local/include/rawtoaces/data/camera`

In the install configuration I'm seeing this line:
`-- Installing: /usr/local/include/rawtoaces/data/camera/.DS_Store`

which, when I try to run rawtoaces, gives me this error

```
/usr/local/include/rawtoaces/data/camera/.DS_Store(1): expected value
Please double check the Camera Sensitivity data (e.g. the increment should be uniform from 380nm to 780nm).
```

Removing the files fixes the issue, but I can see this being a potential problem for users who use Finder to add specsens or other data into rawtoaces.

Additionally, .DS_store files should likely be added to the .gitignore

**Comment by miaoqi** [comment]
I agree and I thought about this issue before. I have added ".DS_store" in the ".gitignore".

I can add something in the code to skip this kind of files. I should have added something a while ago, I thought this may make the code look a little  trivial thus I was hesitating. I agree that it is important.
