### ISSUE TITLE
Fix broken links in "README.md" file.

### ISSUE THREAD

**Issue by KelSolaar** [ampas/rawtoaces#66]
A ton of links are broken in the "README.md" file and need to be fixed, e.g. `[http://www.libraw.org/download]()` ---> `[http://www.libraw.org/download](http://www.libraw.org/download])`.

**Comment by aforsythe** [comment]
This issue was moved to http://www.acescentral.com/t/fix-broken-links-in-readme-md-file/1147

**Comment by agentirons** [comment]
I believe you can keep this one closed.

**Comment by aforsythe** [comment]
Ah yes .. it's merged.  

Sorry for the flood of emails you probably just got.  I was trying to sync the conversations over here with ACEScentral using an integration.  It didn't make clear it would close all the issues here.  I've reopened them.
